version: "1.0.0" # We add version for the reason if we make changes in a file we can easily track it using its version.
name: fastapi
services:
  api:
    build:
      context: ./ # Path to your Dockerfile
      dockerfile: Dockerfile.dev
    container_name: fastapi_app
    ports:
      - "8000:8000"