# FastAPI Project Dockerfile

    ## 🐳 Docker Setup
    # This Dockerfile is used to create a Docker image for the FastAPI application.
    
    # Use an official Python base image
    FROM python:3.12

    LABEL maintainer="Muhammad Farhan Aslam <farhanmehar422538@gmail.com>"
    
    # Set work directory in the container
    # This is where the application code will be copied to
    WORKDIR /app
    
    # Copy current directory contents into the container at /app
    COPY . /app/

    # Install Poetry
    RUN pip install --no-cache-dir poetry

    # configuration to avoid creating virtual environments inside the container
    RUN poetry config virtualenvs.create false

    # Install dependencies
    # Install dependencies using Poetry
    RUN poetry install --no-root

    # Install system dependencies
    RUN apt-get update && apt-get install -y \
        build-essential \
        gcc \
        libpq-dev \
        && rm -rf /var/lib/apt/lists/*
    
    # Expose FastAPI port
    EXPOSE 8000
    
    # Run the FastAPI app
    CMD ["poetry", "run", "uvicorn", "fastapi_project.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    